stages:
- stage: StageA
  jobs:
  # Set an output variable in a lifecycle hook of a deployment job executing runOnce strategy.
  - deployment: A
    pool:
      vmImage: 'ubuntu-16.04'
    environment: staging
    strategy:                  
      runOnce:
        deploy:
          steps:
          - bash: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the deployment variable value"
            name: setvarStep
          - bash: echo "##vso[task.setvariable variable=RunStageB;isOutput=true]true"
            name: setrunStep
          - bash: echo $(setvarStep.myOutputVar)
            name: echovar
          - bash: echo $(setrunStep.RunStageB)
            name: echorun

  # Map the variable from the job.
  - job: B
    dependsOn: A
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      myVarFromDeploymentJob: $[ dependencies.A.outputs['A.setvarStep.myOutputVar'] ]
    steps:
    - script: "echo $(myVarFromDeploymentJob)"
      name: echovar

- stage: StageB
  dependsOn: StageA
  condition: eq(dependencies.StageA.A.outputs['A.setrunStep.RunStageB'], 'true')

  jobs:
  # Set an output variable in a lifecycle hook of a deployment job executing runOnce strategy.
  - deployment: C
    pool:
      vmImage: 'ubuntu-16.04'
    environment: staging
    variables:
      myVarFromDeploymentStage: $[ stageDependencies.StageA.A.outputs['A.setvarStep.myOutputVar'] ]
      myBoolVarFromDeploymentStage: $[ stageDependencies.StageA.A.outputs['A.setrunStep.RunStageB'] ]
    strategy:                  
      runOnce:
        deploy:
          steps:      
          - bash: echo $(myVarFromDeploymentStage) #outputs this is the deployment variable value
            name: echovartrytwo
          - bash: echo $(myBoolVarFromDeploymentStage) # outputs true
            name: echovartrybool 
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                
                env | sort
