stages:
- stage: StageA
  jobs:
  - deployment: A1
    pool:
      vmImage: 'ubuntu-16.04'
    environment: env1
    strategy:                  
      runOnce:
        deploy:
          steps:
          - bash: echo "##vso[task.setvariable variable=RunStageB;isOutput=true]true"
            name: setvarStep
          - bash: echo $(System.JobName)
          - bash: echo "##vso[task.setvariable variable=shouldrun;isOutput=true]true"


- stage: StageB
  dependsOn: 
    - StageA
  condition: eq(stageDependencies.StageA.outputs['A1.setvarStep.RunStageB'], 'true')
  variables:
    myOutputVar: $[stageDependencies.StageA.outputs['A1.setvarStep.RunStageB']]
  jobs:
  - deployment: B1
    environment: env1
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:                  
      runOnce:
        deploy:
          steps:
          - bash: echo $(myOutputVar)
