trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm init react-app my-app
    npm run build
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    Contents: 'build/**' ## update to match what you want to copy
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# - script: echo $(Build.StagingDirectory) ## output staging directory
# - powershell: dir ## output contents of root directory
# - powershell: Get-ChildItem -Path build -Recurse -Force ## verify there are contents in build

- task: PublishBuildArtifacts@1
  inputs: 
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' # dist or build files
    ArtifactName: 'www'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'retro-demo'
    appType: 'webAppLinux'
    appName: 'pipelinesApp'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'